name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests ${{ matrix.java }}
    runs-on: ubuntu-latest

    if: false

    strategy:
      matrix:
        java: [adopt@1.8, adopt@1.11]

    steps:
      - run: echo ${{ matrix.java }}
